AVR2025: IEEE 802.15.4 MAC Reference Manual
Microcontroller Wireless Solutions
pal_timer.c File Reference
Detailed Description
Timer related functions for the ATmega128RFA1 Mega RF Single Chip.
This file implements timer related functions for the ATmega128RFA1.
Id
pal_timer.c 22386 2010-06-30 15:51:38Z sschneid
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Definition in file pal_timer.c.
Defines
#define CONCAT(a, b) a##b
#define DELAY_WITHOUT_IRQS_US (100)
#define MASK_LOW27 (0x07FFFFFFuL)
#define MASK_LOW28 (0x0FFFFFFFuL)
#define PAL_US_PER_SYMBOLS (16)
#define SC_READ32(reg)
#define SC_WRITE32(reg, val)
Functions
static bool compare_time (uint32_t t1, uint32_t t2)
void internal_timer_handler (void)
void pal_get_current_time (uint32_t *current_time)
bool pal_is_timer_running (uint8_t timer_id)
retval_t pal_start_high_priority_timer (uint8_t timer_id, uint16_t timer_count, FUNC_PTR timer_cb, void *param_cb)
retval_t pal_stop_high_priority_timer (uint8_t timer_id)
void pal_timer_delay (uint16_t delay)
void pal_timer_source_select (source_type_t source)
retval_t pal_timer_start (uint8_t timer_id, uint32_t timer_count, timeout_type_t timeout_type, FUNC_PTR timer_cb, void *param_cb)
retval_t pal_timer_stop (uint8_t timer_id)
void pal_trx_read_timestamp (uint32_t *timestamp)
static void prog_ocr (void)
static uint32_t sc_read32 (volatile uint8_t *hh, volatile uint8_t *hl, volatile uint8_t *lh, volatile uint8_t *ll)
void SCNT_CMP1_vect (void)
void SCNT_CMP2_vect (void)
void SCNT_CMP3_vect (void)
static void start_absolute_timer (uint8_t timer_id, uint32_t point_in_time, FUNC_PTR handler_cb, void *parameter)
void timer_init (void)
void timer_service (void)
Define Documentation
#define CONCAT (a, b) a##b
String concatenation by preprocessor used to create proper register names.
Definition at line 79 of file pal_timer.c.
#define DELAY_WITHOUT_IRQS_US (100)
Maximum delay in us that function pal_timer_delay() is running with interrupts disabled. If the delay is larger, interrupts need to be enabled inbetween.
Definition at line 103 of file pal_timer.c.
Referenced by pal_timer_delay().
#define MASK_LOW27 (0x07FFFFFFuL)
Unmask upper 5 bits.
Definition at line 117 of file pal_timer.c.
Referenced by compare_time().
#define MASK_LOW28 (0x0FFFFFFFuL)
Unmask upper 4 bits.
Definition at line 114 of file pal_timer.c.
Referenced by pal_start_high_priority_timer(), pal_timer_start(), and start_absolute_timer().
#define PAL_US_PER_SYMBOLS (16)
Conversion factor: us per symbol for 2,4 GHz.
Definition at line 120 of file pal_timer.c.
Referenced by pal_get_current_time(), pal_start_high_priority_timer(), pal_timer_start(), and pal_trx_read_timestamp().
#define SC_READ32 (reg)
Value:
sc_read32(&CONCAT(reg,HH), \
                                                  &CONCAT(reg,HL), \
                                                  &CONCAT(reg,LH), \
                                                  &CONCAT(reg,LL))
Creates proper subregister names and reads the corresponding values.
Definition at line 82 of file pal_timer.c.
Referenced by pal_get_current_time(), pal_start_high_priority_timer(), pal_timer_start(), pal_trx_read_timestamp(), and prog_ocr().
#define SC_WRITE32 (reg, val)
Value:
do { \
    union { uint8_t a[4]; uint32_t v; } x; \
    x.v = val; \
    CONCAT(reg,HH) = x.a[3]; \
    CONCAT(reg,HL) = x.a[2]; \
    CONCAT(reg,LH) = x.a[1]; \
    CONCAT(reg,LL) = x.a[0]; \
} while(0)
Creates proper subregister names and writes the corresponding values.
Definition at line 88 of file pal_timer.c.
Referenced by pal_start_high_priority_timer(), prog_ocr(), and timer_init().
Function Documentation
static bool compare_time (uint32_t t1, uint32_t t2) [inline, static]
Compares two 32-bit time values.
This function compares two true 32-bit time values t1 and t2 and returns true if t1 is less than t2.
Parameters:
t1 Time
t2 Time
Returns:
true If t1 is less than t2 when MSBs are same, false otherwise.
Definition at line 186 of file pal_timer.c.
References MASK_LOW27.
Referenced by prog_ocr(), and start_absolute_timer().
void internal_timer_handler (void)
Internal timer handler.
This function checks for expired timers and rearranges the running timer queue head and expired timer queue head and tail if there are any expired timers.
Definition at line 981 of file pal_timer.c.
References ENTER_CRITICAL_REGION, LEAVE_CRITICAL_REGION, and prog_ocr().
Referenced by pal_timer_stop(), start_absolute_timer(), and timer_service().
void pal_get_current_time (uint32_t * current_time)
Gets current time.
This function returns the current time.
Parameters:
[out] current_time Current system time
Definition at line 753 of file pal_timer.c.
References PAL_US_PER_SYMBOLS, and SC_READ32.
bool pal_is_timer_running (uint8_t timer_id)
Checks if the timer with the requested timer identifier is running.
Checks if the timer of requested timer identifier is running.
Parameters:
timer_id Timer identifier
Returns:
true if timer with requested timer id is running,
false otherwise.
Definition at line 883 of file pal_timer.c.
retval_t pal_start_high_priority_timer (uint8_t timer_id, uint16_t timer_count, FUNC_PTR timer_cb, void * param_cb)
Starts high priority timer.
This function starts a high priority timer for the specified timeout.
Parameters:
timer_id Timer identifier
timer_count Timeout in microseconds
timer_cb Callback handler invoked upon timer expiry
param_cb Argument for the callback handler
Returns:
PAL_TMR_INVALID_ID if the identifier is undefined,
MAC_INVALID_PARAMETER if the callback function for this timer is NULL,
PAL_TMR_ALREADY_RUNNING if the timer is already running, or
MAC_SUCCESS if timer is started successfully.
Definition at line 387 of file pal_timer.c.
References ENTER_CRITICAL_REGION, LEAVE_CRITICAL_REGION, MAC_INVALID_PARAMETER, MAC_SUCCESS, MASK_LOW28, PAL_TMR_ALREADY_RUNNING, PAL_TMR_INVALID_ID, PAL_US_PER_SYMBOLS, SC_READ32, and SC_WRITE32.
retval_t pal_stop_high_priority_timer (uint8_t timer_id)
Stops a high priority timer.
This function stops a high priority timer.
Parameters:
timer_id Timer identifier
Returns:
PAL_TMR_NOT_RUNNING if the timer id does not match with the high priority timer register, or
MAC_SUCCESS otherwise.
Definition at line 632 of file pal_timer.c.
References ENTER_CRITICAL_REGION, LEAVE_CRITICAL_REGION, MAC_SUCCESS, and PAL_TMR_NOT_RUNNING.
void pal_timer_delay (uint16_t delay)
Performes blocking delay.
Generates blocking delay.
This functions performs a blocking delay of the specified time.
Parameters:
delay in microseconds
Definition at line 786 of file pal_timer.c.
References DELAY_WITHOUT_IRQS_US.
Referenced by pal_alert().
void pal_timer_source_select (source_type_t source)
Selects timer clock source.
This function selects the clock source of the timer.
Unused for the ATmega128RFA1 because the MAC symbol counter automatically switches from XTAL1 to RTC when the transceiver module is put to sleep.
Parameters:
source
TMR_CLK_SRC_DURING_TRX_SLEEP if clock source during sleep is to be selected, and
TMR_CLK_SRC_DURING_TRX_AWAKE if clock source while being awake is selected.
Definition at line 738 of file pal_timer.c.
retval_t pal_timer_start (uint8_t timer_id, uint32_t timer_count, timeout_type_t timeout_type, FUNC_PTR timer_cb, void * param_cb)
Starts regular timer.
Start regular timer.
This function starts a regular timer and registers the corresponding callback function to handle the timeout event.
Parameters:
timer_id Timer identifier
timer_count Timeout in microseconds
timeout_type TIMEOUT_RELATIVE / TIMEOUT_ABSOLUTE
timer_cb Callback handler invoked upon timer expiry
param_cb Argument for the callback handler
Returns:
PAL_TMR_INVALID_ID if the timer identifier is undefined,
MAC_INVALID_PARAMETER if the callback function for this timer is NULL or timeout_type is invalid,
PAL_TMR_ALREADY_RUNNING if the timer is already running,
MAC_SUCCESS if timer is started, or
PAL_TMR_INVALID_TIMEOUT if timeout is not within the timeout range.
Definition at line 301 of file pal_timer.c.
References MAC_INVALID_PARAMETER, MAC_SUCCESS, MASK_LOW28, MAX_TIMEOUT, MIN_TIMEOUT, PAL_TMR_ALREADY_RUNNING, PAL_TMR_INVALID_ID, PAL_TMR_INVALID_TIMEOUT, PAL_US_PER_SYMBOLS, SC_READ32, start_absolute_timer(), TIMEOUT_ABSOLUTE, and TIMEOUT_RELATIVE.
retval_t pal_timer_stop (uint8_t timer_id)
Stops a running timer.
This function stops a running timer with the specified timer_id.
Parameters:
timer_id Timer identifier
Returns:
MAC_SUCCESS if the timer was stopped successfully,
PAL_TMR_NOT_RUNNING if the specified timer is not running,
PAL_TMR_INVALID_ID if the specified timer id is undefined.
Definition at line 470 of file pal_timer.c.
References ENTER_CRITICAL_REGION, internal_timer_handler(), LEAVE_CRITICAL_REGION, MAC_SUCCESS, PAL_TMR_INVALID_ID, PAL_TMR_NOT_RUNNING, and prog_ocr().
void pal_trx_read_timestamp (uint32_t * timestamp)
Provides timestamp of the last received frame.
This function provides the timestamp (in microseconds) of the last received frame.
Parameters:
[out] timestamp in microseconds
Definition at line 772 of file pal_timer.c.
References PAL_US_PER_SYMBOLS, and SC_READ32.
static void prog_ocr (void) [static]
Programs the output compare register SCOCR1.
This function programs the SCOCR1 register with the timeout value of the timer present at the head of the running timer queue.
Definition at line 931 of file pal_timer.c.
References compare_time(), SC_READ32, and SC_WRITE32.
Referenced by internal_timer_handler(), pal_timer_stop(), and start_absolute_timer().
static uint32_t sc_read32 (volatile uint8_t * hh, volatile uint8_t * hl, volatile uint8_t * lh, volatile uint8_t * ll) [inline, static]
Reads the 32-bit timer register in the required order of bytes.
Parameters:
hh hh octet of 32-bit register
hl hl octet of 32-bit register
lh lh octet of 32-bit register
ll ll octet of 32-bit register
Returns:
uint32_t Value of timer register
void SCNT_CMP1_vect (void)
Timer1 COMPA ISR.
This is the interrupt service routine for timer1 output compare match. It is triggered when a timer expires.
void SCNT_CMP2_vect (void)
ISR to limit the MAC symbol counter to 28 bits width.
The current counter value will be advanced to -1, so it rolls over to 0 at the next timer tick.
void SCNT_CMP3_vect (void)
ISR for high priority timer, triggered by SCOCR2.
This is the interrupt service routine for SCOCR2 output compare match. It is triggered when a high priority timer expires.
static void start_absolute_timer (uint8_t timer_id, uint32_t point_in_time, FUNC_PTR handler_cb, void * parameter) [static]
Start a timer by setting its absolute expiration time.
This function starts a timer which should expire at the point_in_time value and upon timer expiry the function held by the handler is called.
Parameters:
timer_id Timer identifier
point_in_time Absolute expiration time in microseconds
handler_cb Function called upon timer expiry
parameter Parameter passed to the expired timer handler
Definition at line 1045 of file pal_timer.c.
References compare_time(), ENTER_CRITICAL_REGION, internal_timer_handler(), LEAVE_CRITICAL_REGION, MASK_LOW28, and prog_ocr().
Referenced by pal_timer_start().
void timer_init (void)
This function is called to initialize the timer module.
Definition at line 662 of file pal_timer.c.
References SC_WRITE32.
Referenced by pal_init().
void timer_service (void)
Timer handling services.
This Function performs timer handling services. It calls functions which are responsible 1) to put the expired timer into the expired timer queue, and 2) to service expired timers and call the respective callback.
Definition at line 220 of file pal_timer.c.
References ENTER_CRITICAL_REGION, internal_timer_handler(), and LEAVE_CRITICAL_REGION.
Referenced by pal_task().