AVR2025: IEEE 802.15.4 MAC Reference Manual
Microcontroller Wireless Solutions
pal.c File Reference
Detailed Description
General PAL functions for AVR ATxmega MCUs.
This file implements generic PAL function for AVR ATxmega MCUs.
Id
pal.c 21606 2010-04-14 14:09:54Z uwalter
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Definition in file pal.c.
Functions
static void eeprom_flush_buffer (void)
static uint8_t eeprom_read_byte (uint8_t *addr)
static void eeprom_wait_for_NVM (void)
static void eeprom_write_byte (uint8_t addr, uint8_t value)
static void NVM_EXEC ()
void pal_alert (void)
retval_t pal_init (void)
retval_t pal_ps_get (ps_type_t ps_type, uint16_t start_addr, uint16_t length, void *value)
retval_t pal_ps_set (uint16_t start_addr, uint16_t length, void *value)
void pal_task (void)
Variables
volatile uint16_t sys_time
Function Documentation
static void eeprom_flush_buffer (void) [static]
Flush temporary EEPROM page buffer.
This function flushes the EEPROM page buffers. This function will cancel any ongoing EEPROM page buffer loading operations, if any. This function also works for memory mapped EEPROM access. Implementation used from application note AVR1315.
Note:
The EEPROM write operations will automatically flush the buffer for you.
Definition at line 192 of file pal.c.
References eeprom_wait_for_NVM(), and NVM_EXEC().
Referenced by eeprom_write_byte().
static uint8_t eeprom_read_byte (uint8_t * addr) [static]
Read one byte from EEPROM address.
Implementation used from application note AVR1315.
Parameters:
addr Pointer to EEPROM address
Returns:
Value at EEPROM address
Definition at line 159 of file pal.c.
References eeprom_wait_for_NVM(), and NVM_EXEC().
Referenced by pal_ps_get(), and pal_ps_set().
static void eeprom_wait_for_NVM (void) [inline, static]
Wait for any NVM access to finish, including EEPROM.
This function is blcoking and waits for any NVM access to finish, including EEPROM. Use this function before any EEPROM accesses, if you are not certain that any previous operations are finished yet, like an EEPROM write. Implementation used from application note AVR1315.
Definition at line 142 of file pal.c.
Referenced by eeprom_flush_buffer(), and eeprom_read_byte().
static void eeprom_write_byte (uint8_t addr, uint8_t value) [static]
Write one byte to EEPROM address.
Implementation used from application note AVR1315.
Parameters:
addr EEPROM address
Value for EEPROM address
Definition at line 213 of file pal.c.
References eeprom_flush_buffer(), and NVM_EXEC().
Referenced by pal_ps_set().
static void NVM_EXEC () [inline, static]
Non-Volatile Memory Execute Command.
This macro set the CCP register before setting the CMDEX bit in the NVM.CTRLA register. Implementation used from application note AVR1315.
Note:
The CMDEX bit must be set within 4 clock cycles after setting the protection byte in the CCP register.
Definition at line 117 of file pal.c.
Referenced by eeprom_flush_buffer(), eeprom_read_byte(), and eeprom_write_byte().
void pal_alert (void)
Alert indication.
This Function can be used by any application to indicate an error condition. The function is blocking and does never return.
Definition at line 329 of file pal.c.
References pal_timer_delay().
retval_t pal_init (void)
Initialization of PAL.
This function initializes the PAL.
Returns:
MAC_SUCCESS if PAL initialization is successful, FAILURE otherwise
Definition at line 59 of file pal.c.
References clock_init(), event_system_init(), gpio_init(), interrupt_system_init(), MAC_SUCCESS, and trx_interface_init().
retval_t pal_ps_get (ps_type_t ps_type, uint16_t start_addr, uint16_t length, void * value)
Get data from persistence storage.
Parameters:
[in] ps_type Persistence storage type
[in] start_addr Start offset within EEPROM
[in] length Number of bytes to read from EEPROM
[out] value Data from persistence storage
Returns:
MAC_SUCCESS if everything went OK else FAILURE
Definition at line 251 of file pal.c.
References eeprom_read_byte(), EXTERN_EEPROM, FAILURE, INTERN_EEPROM, MAC_INVALID_PARAMETER, and MAC_SUCCESS.
retval_t pal_ps_set (uint16_t start_addr, uint16_t length, void * value)
Write data to persistence storage.
Parameters:
[in] start_addr Start address offset within EEPROM
[in] length Number of bytes to be written to EEPROM
[in] value Data to persistence storage
Returns:
MAC_SUCCESS if everything went OK else FAILURE
Definition at line 296 of file pal.c.
References eeprom_read_byte(), eeprom_write_byte(), FAILURE, and MAC_SUCCESS.
void pal_task (void)
Services timer and sio handler.
This function calls sio & timer handling functions.
Definition at line 81 of file pal.c.
References timer_service().