AVR2025: IEEE 802.15.4 MAC Reference Manual
Microcontroller Wireless Solutions
pal_board.c File Reference
Detailed Description
PAL board specific functionality.
This file implements PAL board specific functionality.
Id
pal_board.c 19228 2009-11-13 11:52:02Z sschneid
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Definition in file pal_board.c.
Functions
void clock_init (void)
void event_system_init (void)
void gpio_init (void)
void interrupt_system_init (void)
void pal_button_init (void)
button_state_t pal_button_read (button_id_t button_no)
bool pal_calibrate_rc_osc (void)
void pal_led (led_id_t led_no, led_action_t led_setting)
void pal_led_init (void)
void pal_trx_read_timestamp (uint32_t *timestamp)
void timer_init_non_generic (void)
Function Documentation
void clock_init (void)
Initialize the clock of the ATxmega.
Definition at line 110 of file pal_board.c.
Referenced by pal_init().
void event_system_init (void)
Initialize the event system of the ATxmega.
Definition at line 85 of file pal_board.c.
Referenced by pal_init().
void gpio_init (void)
Initializes the GPIO pins.
This function is used to initialize the port pins used to connect the microcontroller to transceiver.
Definition at line 150 of file pal_board.c.
Referenced by pal_init().
void interrupt_system_init (void)
Initialize the interrupt system of the ATxmega.
Definition at line 99 of file pal_board.c.
Referenced by pal_init().
void pal_button_init (void)
Initialize the button.
Button initialization.
Definition at line 249 of file pal_board.c.
button_state_t pal_button_read (button_id_t button_no)
Read button.
Button handling.
Parameters:
button_no Button ID
Definition at line 262 of file pal_board.c.
References BUTTON_OFF, and BUTTON_PRESSED.
bool pal_calibrate_rc_osc (void)
Calibrates the internal RC oscillator.
This function calibrates the internal RC oscillator.
Returns:
True since the RC oscillator is always calibrated automatically at startup by hardware itself
Definition at line 75 of file pal_board.c.
void pal_led (led_id_t led_no, led_action_t led_setting)
Control LED status.
LED handling.
Parameters:
[in] led_no LED ID
[in] led_setting LED_ON, LED_OFF, LED_TOGGLE
Definition at line 214 of file pal_board.c.
References LED_OFF, LED_ON, and LED_TOGGLE.
void pal_led_init (void)
Initialize LEDs.
LED initialization.
Definition at line 199 of file pal_board.c.
void pal_trx_read_timestamp (uint32_t * timestamp)
Provides timestamp of the last received frame.
This function provides the timestamp (in microseconds) of the last received frame.
Parameters:
[out] Timestamp in microseconds
Definition at line 51 of file pal_board.c.