AVR2025: IEEE 802.15.4 MAC Reference Manual
Microcontroller Wireless Solutions
pal.h File Reference
Detailed Description
PAL related APIs.
This header file declares prototypes of PAL APIs, enumerations used by TAL and MAC.
Id
pal.h 22804 2010-08-09 09:10:33Z yogesh.bellan
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Definition in file pal.h.
Defines
#define ADD_TIME(a, b) ((a) + (b))
#define PAL_RST_HIGH() RST_HIGH()
#define PAL_RST_LOW() RST_LOW()
#define PAL_SLP_TR_HIGH() SLP_TR_HIGH()
#define PAL_SLP_TR_LOW() SLP_TR_LOW()
#define pal_trx_irq_dis() DISABLE_TRX_IRQ()
#define pal_trx_irq_dis_tstamp() DISABLE_TRX_IRQ_TSTAMP()
#define pal_trx_irq_en() ENABLE_TRX_IRQ()
#define pal_trx_irq_en_tstamp() ENABLE_TRX_IRQ_TSTAMP()
#define pal_trx_irq_flag_clr() CLEAR_TRX_IRQ()
#define pal_trx_irq_flag_clr_tstamp() CLEAR_TRX_IRQ_TSTAMP()
#define SUB_TIME(a, b) ((a) - (b))
Typedefs
typedef enum button_state_tag button_state_t
typedef enum led_action_tag led_action_t
typedef enum pin_state_tag pin_state_t
typedef enum ps_id_tag ps_id_t
typedef enum ps_type_tag ps_type_t
typedef enum pwr_mode_tag pwr_mode_t
typedef enum sio_serial_tag sio_serial_t
typedef enum source_type_tag source_type_t
typedef enum timeout_type_tag timeout_type_t
Enumerations
enum button_state_tag { BUTTON_PRESSED, BUTTON_OFF }
enum led_action_tag { LED_ON, LED_OFF, LED_TOGGLE }
enum pin_state_tag { LOW, HIGH }
enum ps_id_tag { PS_IEEE_ADDR, PS_XTAL_TRIM }
enum ps_type_tag { INTERN_EEPROM, EXTERN_EEPROM }
enum pwr_mode_tag { SYSTEM_SLEEP }
enum sio_serial_tag { SIO_0, SIO_1, SIO_2 }
enum source_type_tag { TMR_CLK_SRC_DURING_TRX_SLEEP, TMR_CLK_SRC_DURING_TRX_AWAKE }
enum timeout_type_tag { TIMEOUT_RELATIVE, TIMEOUT_ABSOLUTE }
Functions
static uint32_t pal_add_time_us (uint32_t a, uint32_t b)
void pal_alert (void)
void pal_button_init (void)
button_state_t pal_button_read (button_id_t button_no)
bool pal_calibrate_rc_osc (void)
uint16_t pal_generate_rand_seed (void)
void pal_get_current_time (uint32_t *current_time)
static void pal_global_irq_disable (void)
static void pal_global_irq_enable (void)
retval_t pal_init (void)
bool pal_is_timer_running (uint8_t timer_id)
void pal_led (led_id_t led_no, led_action_t led_setting)
void pal_led_init (void)
retval_t pal_ps_get (ps_type_t ps_type, uint16_t start_addr, uint16_t length, void *value)
retval_t pal_ps_set (uint16_t start_addr, uint16_t length, void *value)
retval_t pal_pwr_mode (pwr_mode_t pwr_mode)
retval_t pal_sio_init (uint8_t sio_unit)
uint8_t pal_sio_rx (uint8_t sio_unit, uint8_t *data, uint8_t max_length)
uint8_t pal_sio_tx (uint8_t sio_unit, uint8_t *data, uint8_t length)
void pal_spi_done_cb_init (void *spi_done_cb)
retval_t pal_start_high_priority_timer (uint8_t timer_id, uint16_t timer_count, FUNC_PTR timer_cb, void *param_cb)
retval_t pal_stop_high_priority_timer (uint8_t timer_id)
static uint32_t pal_sub_time_us (uint32_t a, uint32_t b)
void pal_task (void)
void pal_timer_delay (uint16_t delay)
void pal_timer_source_select (source_type_t source)
retval_t pal_timer_start (uint8_t timer_id, uint32_t timer_count, timeout_type_t timeout_type, FUNC_PTR timer_cb, void *param_cb)
retval_t pal_timer_stop (uint8_t timer_id)
void pal_trx_aes_wrrd (uint8_t addr, uint8_t *idata, uint8_t length)
uint8_t pal_trx_bit_read (uint8_t addr, uint8_t mask, uint8_t pos)
void pal_trx_bit_write (uint8_t reg_addr, uint8_t mask, uint8_t pos, uint8_t new_value)
void pal_trx_frame_read (uint8_t *data, uint8_t length)
void pal_trx_frame_write (uint8_t *data, uint8_t length)
void pal_trx_irq_init (FUNC_PTR trx_irq_cb)
void pal_trx_irq_init_tstamp (FUNC_PTR trx_irq_cb)
void pal_trx_read_timestamp (uint32_t *timestamp)
uint8_t pal_trx_reg_read (uint8_t addr)
void pal_trx_reg_write (uint8_t addr, uint8_t data)
void pal_trx_sram_read (uint8_t addr, uint8_t *data, uint8_t length)
void pal_trx_sram_write (uint8_t addr, uint8_t *data, uint8_t length)
Define Documentation
#define ADD_TIME (a, b) ((a) + (b))
Adds two time values
Definition at line 45 of file pal.h.
Referenced by pal_add_time_us(), and pal_timer_start().
#define PAL_RST_HIGH () RST_HIGH()
Macro to set Reset pin to high
Definition at line 599 of file pal.h.
#define PAL_RST_LOW () RST_LOW()
Macro to set Reset pin to low
Definition at line 601 of file pal.h.
#define PAL_SLP_TR_HIGH () SLP_TR_HIGH()
Macro to set SLP_TR pin to high
Definition at line 603 of file pal.h.
#define PAL_SLP_TR_LOW () SLP_TR_LOW()
Macro to set SLP_TR pin to low
Definition at line 605 of file pal.h.
#define pal_trx_irq_dis () DISABLE_TRX_IRQ()
Disables the transceiver main interrupt.
This macro is only available for non-single chip transceivers, since in single chip transceivers there is no separation between disabling transceiver interrupts at the transceiver, and clearing the IRQ mask at the MCU. Therefore the transceiver interrupts in single chips are disabled by clearing the MCU IRQ mask.
Definition at line 366 of file pal.h.
#define pal_trx_irq_dis_tstamp () DISABLE_TRX_IRQ_TSTAMP()
Disables the transceiver timestamp interrupt.
This macro is only available for non-single chip transceivers, since in single chip transceivers there is no separation between disabling transceiver interrupts at the transceiver, and clearing the IRQ mask at the MCU. Therefore the transceiver interrupts in single chips are disabled by clearing the MCU IRQ mask.
Definition at line 379 of file pal.h.
#define pal_trx_irq_en () ENABLE_TRX_IRQ()
Enables the transceiver main interrupt.
This macro is only available for non-single chip transceivers, since in single chip transceivers there is no separation between enabling transceiver interrupts at the transceiver, and setting the IRQ mask at the MCU. Therefore the transceiver interrupts in single chips are enabled by setting the MCU IRQ mask.
Definition at line 340 of file pal.h.
#define pal_trx_irq_en_tstamp () ENABLE_TRX_IRQ_TSTAMP()
Enables the transceiver timestamp interrupt.
This macro is only available for non-single chip transceivers, since in single chip transceivers there is no separation between enabling transceiver interrupts at the transceiver, and setting the IRQ mask at the MCU. Therefore the transceiver interrupts in single chips are enabled by setting the MCU IRQ mask.
Definition at line 353 of file pal.h.
#define pal_trx_irq_flag_clr () CLEAR_TRX_IRQ()
Clears the transceiver main interrupt.
Definition at line 387 of file pal.h.
#define pal_trx_irq_flag_clr_tstamp () CLEAR_TRX_IRQ_TSTAMP()
Clears the transceiver timestamp interrupt.
Definition at line 394 of file pal.h.
#define SUB_TIME (a, b) ((a) - (b))
Subtracts two time values
Definition at line 50 of file pal.h.
Referenced by pal_sub_time_us(), and pal_timer_start().
Typedef Documentation
typedef enum button_state_tag button_state_t
Button action.
typedef enum led_action_tag led_action_t
LED action.
typedef enum pin_state_tag pin_state_t
Pin State
typedef enum ps_id_tag ps_id_t
IDs for persistence storage access.
typedef enum ps_type_tag ps_type_t
IDs for persistence storage type.
typedef enum pwr_mode_tag pwr_mode_t
Power modes.
typedef enum sio_serial_tag sio_serial_t
Stream I/O to serial mapping enumeration
typedef enum source_type_tag source_type_t
Timer clock source type
typedef enum timeout_type_tag timeout_type_t
Timeout type
Enumeration Type Documentation
enum button_state_tag
Button action.
Enumerator:
BUTTON_PRESSED Button is pressed.
BUTTON_OFF Button is released.
Definition at line 147 of file pal.h.
enum led_action_tag
LED action.
Enumerator:
LED_ON Switch LED on.
LED_OFF Switch LED off.
LED_TOGGLE Toggle LED.
Definition at line 133 of file pal.h.
enum pin_state_tag
Pin State
Enumerator:
LOW Pin state low
HIGH Pin state high
Definition at line 58 of file pal.h.
enum ps_id_tag
IDs for persistence storage access.
Definition at line 111 of file pal.h.
enum ps_type_tag
IDs for persistence storage type.
Enumerator:
INTERN_EEPROM MCU Internal EEPROM
EXTERN_EEPROM External EEPROM
Definition at line 121 of file pal.h.
enum pwr_mode_tag
Power modes.
Definition at line 159 of file pal.h.
enum sio_serial_tag
Stream I/O to serial mapping enumeration
Enumerator:
SIO_0 UART 0
SIO_1 UART 1
SIO_2 USB 0
Definition at line 71 of file pal.h.
enum source_type_tag
Timer clock source type
Enumerator:
TMR_CLK_SRC_DURING_TRX_SLEEP Identifier for timer clock source during sleep
TMR_CLK_SRC_DURING_TRX_AWAKE Identifier for timer clock source while being awake
Definition at line 100 of file pal.h.
enum timeout_type_tag
Timeout type
Enumerator:
TIMEOUT_RELATIVE The timeout is relative to the current time.
TIMEOUT_ABSOLUTE The timeout is an absolute value.
Definition at line 87 of file pal.h.
Function Documentation
static uint32_t pal_add_time_us (uint32_t a, uint32_t b) [inline, static]
Adds two time values.
Parameters:
a Time value 1
b Time value 2
Returns:
Addition of a and b
Definition at line 574 of file pal.h.
References ADD_TIME.
void pal_alert (void)
Alert indication.
This Function can be used by any application to indicate an error condition. The function is blocking and does never return.
Definition at line 329 of file pal.c.
References pal_timer_delay().
void pal_button_init (void)
Button initialization.
Definition at line 249 of file pal_board.c.
button_state_t pal_button_read (button_id_t button_no)
Button handling.
Parameters:
button_no Button id
Button handling.
Parameters:
button_no Button ID
Definition at line 262 of file pal_board.c.
References BUTTON_OFF, and BUTTON_PRESSED.
bool pal_calibrate_rc_osc (void)
Calibrates the internal RC oscillator.
Returns:
True if calibration is successful, false otherwise.
This function calibrates the internal RC oscillator.
Returns:
True since the RC oscillator is always calibrated automatically at startup by hardware itself
Definition at line 75 of file pal_board.c.
uint16_t pal_generate_rand_seed (void)
Generation of random seed for function srand() in case this is not supported by the transceiver (e.g. AT86RF230).
Returns:
uint16_t Random number to be used as seed for function srand()
void pal_get_current_time (uint32_t * current_time)
Gets current time.
This function returns the current time.
Parameters:
[out] current_time Returns current system time
This function returns the current time.
Parameters:
[out] current_time Current system time
Definition at line 488 of file pal_timer.c.
References gettime().
static void pal_global_irq_disable (void) [inline, static]
Disables the global interrupt.
Definition at line 471 of file pal.h.
References DISABLE_GLOBAL_IRQ.
static void pal_global_irq_enable (void) [inline, static]
Enables the global interrupt.
Definition at line 461 of file pal.h.
References ENABLE_GLOBAL_IRQ.
retval_t pal_init (void)
Initialization of PAL.
This function initializes the PAL. The RC Oscillator is calibrated.
Returns:
MAC_SUCCESS if PAL initialization is successful, FAILURE otherwise
This function initializes the PAL.
Returns:
MAC_SUCCESS if PAL initialization is successful, FAILURE otherwise
Definition at line 59 of file pal.c.
References clock_init(), event_system_init(), gpio_init(), interrupt_system_init(), MAC_SUCCESS, and trx_interface_init().
bool pal_is_timer_running (uint8_t timer_id)
Checks if the timer of requested timer identifier is running.
This function checks if the timer of requested timer identifier is running.
Parameters:
timer_id Timer identifier
Returns:
true if timer with requested timer id is running,
false otherwise.
Checks if the timer of requested timer identifier is running.
Parameters:
timer_id Timer identifier
Returns:
true if timer with requested timer id is running,
false otherwise.
Definition at line 556 of file pal_timer.c.
void pal_led (led_id_t led_no, led_action_t led_setting)
LED handling.
Parameters:
led_no LED id
led_setting LED action
LED handling.
Parameters:
[in] led_no LED ID
[in] led_setting LED_ON, LED_OFF, LED_TOGGLE
Definition at line 214 of file pal_board.c.
References LED_OFF, LED_ON, and LED_TOGGLE.
void pal_led_init (void)
LED initialization.
Definition at line 199 of file pal_board.c.
retval_t pal_ps_get (ps_type_t ps_type, uint16_t start_addr, uint16_t length, void * value)
Get data from persistence storage.
Parameters:
[in] ps_type Persistence storage type
[in] start_addr Start offset within EEPROM
[in] length Number of bytes to read from EEPROM
[out] value Data from persistence storage
Returns:
MAC_SUCCESS if everything went OK else FAILURE
Definition at line 251 of file pal.c.
References eeprom_read_byte(), EXTERN_EEPROM, FAILURE, INTERN_EEPROM, MAC_INVALID_PARAMETER, and MAC_SUCCESS.
retval_t pal_ps_set (uint16_t start_addr, uint16_t length, void * value)
Write data to persistence storage.
Parameters:
[in] start_addr Start address offset within EEPROM
[in] length Number of bytes to be written to EEPROM
[in] value Data to persistence storage
Returns:
MAC_SUCCESS if everything went OK else FAILURE
Definition at line 296 of file pal.c.
References eeprom_read_byte(), eeprom_write_byte(), FAILURE, and MAC_SUCCESS.
retval_t pal_pwr_mode (pwr_mode_t pwr_mode)
Power handling.
Handles power modes for entire system
Parameters:
pwr_mode desired power mode
Returns:
retval_t MAC_SUCCESS
retval_t pal_sio_init (uint8_t sio_unit)
Initializes the requested SIO unit.
This function initializes the requested SIO unit.
Parameters:
sio_unit Specifies the SIO uint to be initialized
Returns:
MAC_SUCCESS if SIO unit is initialized successfully, FAILURE otherwise
uint8_t pal_sio_rx (uint8_t sio_unit, uint8_t * data, uint8_t max_length)
Receives data from selected SIO unit.
This function receives data from the selected SIO unit.
Parameters:
sio_unit Specifies SIO unit
[out] data Pointer to the buffer to store received data
[in] max_length Maximum number of bytes to be received
Returns:
Actual number of received bytes
uint8_t pal_sio_tx (uint8_t sio_unit, uint8_t * data, uint8_t length)
Transmits data through selected SIO unit.
This function transmits data through the selected SIO unit.
Parameters:
sio_unit Specifies the SIO unit
data Pointer to the data to be transmitted is present
length Number of bytes to be transmitted
Returns:
Actual number of transmitted bytes
void pal_spi_done_cb_init (void * spi_done_cb)
SPI done callback initialization.
Parameters:
spi_done_cb Pointer to SPI done callback function
retval_t pal_start_high_priority_timer (uint8_t timer_id, uint16_t timer_count, FUNC_PTR timer_cb, void * param_cb)
Starts high priority timer.
This function starts a high priority timer for the specified timeout.
Parameters:
timer_id Timer identifier
timer_count Timeout in microseconds
timer_cb Callback handler invoked upon timer expiry
param_cb Argument for the callback handler
Returns:
PAL_TMR_INVALID_ID if the identifier is undefined,
MAC_INVALID_PARAMETER if the callback function for this timer is NULL,
PAL_TMR_ALREADY_RUNNING if the timer is already running, or
MAC_SUCCESS if timer is started successfully.
retval_t pal_stop_high_priority_timer (uint8_t timer_id)
Stops a high priority timer.
This function stops a high priority timer.
Parameters:
timer_id Timer identifier
Returns:
PAL_TMR_NOT_RUNNING if the timer id does not match with the high priority timer register, or
MAC_SUCCESS otherwise.
static uint32_t pal_sub_time_us (uint32_t a, uint32_t b) [inline, static]
Subtracts two time values.
Parameters:
a Time value 1
b Time value 2
Returns:
Difference between a and b
Definition at line 589 of file pal.h.
References SUB_TIME.
void pal_task (void)
Services timer and sio handler.
This function calls sio & timer handling functions.
Definition at line 81 of file pal.c.
References timer_service().
void pal_timer_delay (uint16_t delay)
Generates blocking delay.
This functions generates a blocking delay of specified time.
Parameters:
delay in microseconds
Generates blocking delay.
This functions performs a blocking delay of the specified time.
Parameters:
delay in microseconds
Definition at line 502 of file pal_timer.c.
References MIN_DELAY_VAL.
Referenced by pal_alert().
void pal_timer_source_select (source_type_t source)
Selects timer clock source.
This function selects the clock source of the timer.
Parameters:
source
TMR_CLK_SRC_DURING_TRX_SLEEP if clock source during sleep is to be selected, and
TMR_CLK_SRC_DURING_TRX_AWAKE if clock source while being awake is selected.
Definition at line 467 of file pal_timer.c.
References TMR_CLK_SRC_DURING_TRX_SLEEP.
retval_t pal_timer_start (uint8_t timer_id, uint32_t timer_count, timeout_type_t timeout_type, FUNC_PTR timer_cb, void * param_cb)
Start regular timer.
This function starts a regular timer and installs the corresponding callback function handle the timeout event.
Parameters:
timer_id Timer identifier
timer_count Timeout in microseconds
timeout_type TIMEOUT_RELATIVE or TIMEOUT_ABSOLUTE
timer_cb Callback handler invoked upon timer expiry
param_cb Argument for the callback handler
Returns:
PAL_TMR_INVALID_ID if the timer identifier is undefined,
MAC_INVALID_PARAMETER if the callback function for this timer is NULL,
PAL_TMR_ALREADY_RUNNING if the timer is already running.
MAC_SUCCESS if timer is started or
PAL_TMR_INVALID_TIMEOUT if timeout is not within timeout range.
Start regular timer.
This function starts a regular timer and registers the corresponding callback function to handle the timeout event.
Parameters:
timer_id Timer identifier
timer_count Timeout in microseconds
timeout_type TIMEOUT_RELATIVE / TIMEOUT_ABSOLUTE
timer_cb Callback handler invoked upon timer expiry
param_cb Argument for the callback handler
Returns:
PAL_TMR_INVALID_ID if the timer identifier is undefined,
MAC_INVALID_PARAMETER if the callback function for this timer is NULL or timeout_type is invalid,
PAL_TMR_ALREADY_RUNNING if the timer is already running,
MAC_SUCCESS if timer is started, or
PAL_TMR_INVALID_TIMEOUT if timeout is not within the timeout range.
Definition at line 195 of file pal_timer.c.
References ADD_TIME, gettime(), MAC_INVALID_PARAMETER, MAC_SUCCESS, PAL_TMR_ALREADY_RUNNING, PAL_TMR_INVALID_ID, PAL_TMR_INVALID_TIMEOUT, start_absolute_timer(), SUB_TIME, TIMEOUT_ABSOLUTE, and TIMEOUT_RELATIVE.
retval_t pal_timer_stop (uint8_t timer_id)
Stops a running timer.
This function stops a running timer with specified timer_id
Parameters:
timer_id Timer identifier
Returns:
MAC_SUCCESS if timer stopped successfully,
PAL_TMR_NOT_RUNNING if specified timer is not running,
PAL_TMR_INVALID_ID if the specifed timer id is undefined.
This function stops a running timer with the specified timer_id.
Parameters:
timer_id Timer identifier
Returns:
MAC_SUCCESS if the timer was stopped successfully,
PAL_TMR_NOT_RUNNING if the specified timer is not running,
PAL_TMR_INVALID_ID if the specified timer id is undefined.
Definition at line 276 of file pal_timer.c.
References internal_timer_handler(), MAC_SUCCESS, PAL_TMR_INVALID_ID, PAL_TMR_NOT_RUNNING, and prog_ocr().
void pal_trx_aes_wrrd (uint8_t addr, uint8_t * idata, uint8_t length)
Writes and reads data into/from SRAM of the transceiver.
This function writes data into the SRAM of the transceiver and simultaneously reads the bytes.
Parameters:
addr Start address in the SRAM for the write operation
idata Pointer to the data written/read into/from SRAM
length Number of bytes written/read into/from SRAM
uint8_t pal_trx_bit_read (uint8_t addr, uint8_t mask, uint8_t pos)
Subregister read.
Parameters:
addr offset of the register
mask bit mask of the subregister
pos bit position of the subregister
Returns:
value of the read bit(s)
Subregister read.
This function handles the non-blocking SPI transfer. Subregister read
Parameters:
addr offset of the register
mask bit mask of the subregister
pos bit position of the subregister
Returns:
value of the read bit(s)
Definition at line 295 of file pal_trx_access.c.
References pal_trx_reg_read().
void pal_trx_bit_write (uint8_t reg_addr, uint8_t mask, uint8_t pos, uint8_t new_value)
Subregister write.
Parameters:
[in] reg_addr Offset of the register
[in] mask Bit mask of the subregister
[in] pos Bit position of the subregister
[out] new_value Data, which is muxed into the register
Definition at line 315 of file pal_trx_access.c.
References pal_trx_reg_read(), and pal_trx_reg_write().
void pal_trx_frame_read (uint8_t * data, uint8_t length)
Reads frame buffer of the transceiver.
This function reads the frame buffer of the transceiver.
Parameters:
[out] data Pointer to the location to store frame
[in] length Number of bytes to be read from the frame buffer.
Definition at line 171 of file pal_trx_access.c.
void pal_trx_frame_write (uint8_t * data, uint8_t length)
Writes data into frame buffer of the transceiver.
This function writes data into the frame buffer of the transceiver
Parameters:
[in] data Pointer to data to be written into frame buffer
[in] length Number of bytes to be written into frame buffer
Definition at line 215 of file pal_trx_access.c.
void pal_trx_irq_init (FUNC_PTR trx_irq_cb)
Initializes the transceiver main interrupt.
This function sets the microcontroller specific registers responsible for handling the transceiver main interrupt
Parameters:
trx_irq_cb Callback function for the transceiver main interrupt
This function sets the microcontroller specific registers responsible for handling the transceiver main interrupt
Parameters:
trx_irq_cb Callback function for the transceiver main interrupt
Definition at line 60 of file pal_irq.c.
void pal_trx_irq_init_tstamp (FUNC_PTR trx_irq_cb)
Initializes the transceiver timestamp interrupt.
This function sets the microcontroller specific registers responsible for handling the transceiver timestamp interrupt
Parameters:
trx_irq_cb Callback function for the transceiver timestamp interrupt
void pal_trx_read_timestamp (uint32_t * timestamp)
Provides timestamp of the last received frame.
This function provides the timestamp (in microseconds) of the last received frame.
Parameters:
[out] timestamp in microseconds
This function provides the timestamp (in microseconds) of the last received frame.
Parameters:
[out] Timestamp in microseconds
Definition at line 51 of file pal_board.c.
uint8_t pal_trx_reg_read (uint8_t addr)
Reads current value from a transceiver register.
This function reads the current value from a transceiver register.
Parameters:
addr Specifies the address of the trx register from which the data shall be read
Returns:
value of the register read
Definition at line 123 of file pal_trx_access.c.
Referenced by pal_trx_bit_read(), and pal_trx_bit_write().
void pal_trx_reg_write (uint8_t addr, uint8_t data)
Writes data into a transceiver register.
This function writes a value into transceiver register.
Parameters:
addr Address of the trx register
data Data to be written to trx register
Definition at line 81 of file pal_trx_access.c.
Referenced by pal_trx_bit_write().
void pal_trx_sram_read (uint8_t addr, uint8_t * data, uint8_t length)
Reads data from SRAM of the transceiver.
This function reads from the SRAM of the transceiver
Parameters:
[in] addr Start address in SRAM for read operation
[out] data Pointer to the location where data stored
[in] length Number of bytes to be read from SRAM
Definition at line 388 of file pal_trx_access.c.
void pal_trx_sram_write (uint8_t addr, uint8_t * data, uint8_t length)
Writes data into SRAM of the transceiver.
This function writes data into the SRAM of the transceiver
Parameters:
addr Start address in the SRAM for the write operation
data Pointer to the data to be written into SRAM
length Number of bytes to be written into SRAM
Definition at line 340 of file pal_trx_access.c.